language: bash
addons:
  ssh_known_hosts:
  - hro-sma.nl

before_install:
- openssl aes-256-cbc -K $encrypted_71712261ed7b_key -iv $encrypted_71712261ed7b_iv
  -in .travis/deploy_rsa.enc -out deploy_rsa -d

branches:
  only:
  - master

deploy:
  provider: script
  skip_cleanup: true
  script: bash .travis/deploy.sh
  on:
    branch: master