// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using weather.station.server.Data;

namespace weather.station.server.Migrations
{
    [DbContext(typeof(WeatherStationServerContext))]
    partial class WeatherStationServerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("weather.station.server.Models.Device", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DeviceName");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("StudentNumber");

                    b.HasKey("DeviceId");

                    b.ToTable("Device");

                    b.HasData(
                        new { DeviceId = new Guid("1ad80c92-847a-45dd-8397-43f86b417bd9"), DeviceName = "test", Latitude = 5.0, Longitude = 5.0, StudentNumber = "hjdcbs" }
                    );
                });

            modelBuilder.Entity("weather.station.server.Models.WeatherUpdate", b =>
                {
                    b.Property<Guid>("WeatherUpdateId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("DeviceId");

                    b.Property<double>("Humidity");

                    b.Property<double>("TemperatureC");

                    b.Property<DateTime>("TimeStamp");

                    b.Property<double>("Windspeed");

                    b.HasKey("WeatherUpdateId");

                    b.HasIndex("DeviceId");

                    b.ToTable("WeatherUpdate");

                    b.HasData(
                        new { WeatherUpdateId = new Guid("937272a5-3f82-41ec-80af-395d39690be7"), DeviceId = new Guid("1ad80c92-847a-45dd-8397-43f86b417bd9"), Humidity = 5.0, TemperatureC = 5.0, TimeStamp = new DateTime(2018, 11, 6, 16, 58, 58, 715, DateTimeKind.Local), Windspeed = 5.0 }
                    );
                });

            modelBuilder.Entity("weather.station.server.Models.WeatherUpdate", b =>
                {
                    b.HasOne("weather.station.server.Models.Device", "Device")
                        .WithMany("WeatherUpdates")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
